#!/usr/bin/perl

use strict;
use warnings;
use App::OpenZabbixScreen;
use Getopt::Long ();

my $command;
Getopt::Long::GetOptions("command=s" => \$command);
App::OpenZabbixScreen->run( command => $command );
