#!/usr/bin/perl

use strict;
use warnings;
use App::OpenZabbix;
use Getopt::Long ();

my $command;
Getopt::Long::GetOptions("command=s" => \$command);
App::OpenZabbix->run( class => shift, command => $command );
